import{a as i,i as m}from"./assets/vendor-2dcf4ad5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function u(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerpolicy&&(r.referrerPolicy=o.referrerpolicy),o.crossorigin==="use-credentials"?r.credentials="include":o.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(o){if(o.ep)return;o.ep=!0;const r=u(o);fetch(o.href,r)}})();i.defaults.headers.common["x-api-key"]="live_Px7dvVo2xBtlGgvAfuYlwNWpTa0l5UHIWvbfgFeFbc9DLduE10gl8sCkxxlY3C0l";const h=()=>i.get("https://api.thecatapi.com/v1/breeds").then(t=>t.data),y=t=>i.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${t}`).then(e=>e.data[0]),n=document.querySelector(".breed-select"),a=document.querySelector(".loader"),l=document.querySelector(".cat-info"),d=()=>{a.style.display="block",n.style.display="none",l.style.display="none"},p=()=>{a.style.display="none",n.style.display="block",l.style.display="block"},f=t=>{m.error({title:"Error",message:t,position:"topRight"})},g=t=>{const e=document.createElement("option");return e.value=t.id,e.textContent=t.name,e},b=t=>{t.forEach(e=>n.appendChild(g(e)))},v=t=>{console.error("Error fetching breeds:",t),f("Unable to fetch breeds. Please try again later.")},E=()=>{d(),h().then(b).catch(v).finally(p)},L=t=>{d(),y(t).then(e=>{l.innerHTML=`
            <div>
                <img src="${e.url}" alt="${e.breeds[0].name}">

                    <h1><strong>${e.breeds[0].name}</strong></h1>
                    <p>${e.breeds[0].description}</p>
                    <p><strong>Temperament:</strong>
                    ${e.breeds[0].temperament}</p>
                </div>
            `}).catch(e=>{console.error("Error fetching cat information:",e),f("Unable to fetch cat information. Please try again later.")}).finally(p)};n.addEventListener("change",t=>L(t.target.value));E();
//# sourceMappingURL=commonHelpers.js.map
