import{a as i,i as y}from"./assets/vendor-2dcf4ad5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))d(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function h(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerpolicy&&(r.referrerPolicy=o.referrerpolicy),o.crossorigin==="use-credentials"?r.credentials="include":o.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(o){if(o.ep)return;o.ep=!0;const r=h(o);fetch(o.href,r)}})();i.defaults.headers.common["x-api-key"]="live_Px7dvVo2xBtlGgvAfuYlwNWpTa0l5UHIWvbfgFeFbc9DLduE10gl8sCkxxlY3C0l";const m=()=>i.get("https://api.thecatapi.com/v1/breeds").then(t=>t.data),g=t=>i.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${t}`).then(e=>e.data[0]),n=document.querySelector(".breed-select"),a=document.querySelector(".loader"),s=document.querySelector(".cat-info"),p=()=>{a.style.display="block",n.style.display="none",s.style.display="none"};let c=!1;const f=()=>{a.style.display="none",n.style.display="block",s.style.display=c?"block":"none"},b=t=>{y.error({title:"Error",message:t,position:"topRight"})},v=t=>{const e=document.createElement("option");return e.value=t.id,e.textContent=t.name,e},E=t=>{t.forEach(e=>n.appendChild(v(e)))},u=t=>{console.error("Error fetching data:",t),b("Unable to fetch data. Please try again later."),a.style.display="none",s.style.display="none",n.style.display="block",c=!1},L=()=>{p(),m().then(E).catch(u).finally(f)},x=t=>{p(),g(t).then(e=>{if(e&&e.breeds&&e.breeds.length>0)s.innerHTML=`
                <div>
                    <img src="${e.url}" alt="${e.breeds[0].name}">
                    <h1><strong>${e.breeds[0].name}</strong></h1>
                    <p>${e.breeds[0].description}</p>
                    <p><strong>Temperament:</strong> ${e.breeds[0].temperament}</p>
                </div>
                `,c=!0;else throw new Error("No breed data available")}).catch(u).finally(f)};n.addEventListener("change",t=>x(t.target.value));L();
//# sourceMappingURL=commonHelpers.js.map
